### ISSUE TITLE
TODO - Přihlašovací formulář

### ISSUE THREAD

**Issue by mzadrazi** [skallet/minur#1]
- [x] "Tournament edit" -> "Přihlášení"
- [x] "Username" -> "Emailová adresa"
- [x] "Password" -> "Heslo"
- [x] plus možná doplnit (\* povinné), jako je u registračního formuláře
