### ISSUE TITLE
TODO - Zápasy

### ISSUE THREAD

**Issue by mzadrazi** [skallet/minur#3]
- [x] "Přihlášené zápasy" a "Zápasy" v menu -> "Plánování zápasů"
- Do tabulky přidat sloupce:
  - [x] datum
  - [x] čas
  - [x] místo
  - [x] skóre (ať není ve sloupci "akce")
- [x] Sloupec Stav by tam asi ani být nemusel, případně by se to info dalo přesunout do sloupce "Akce".
