### ISSUE TITLE
TODO - Přidání návrhu na termín

### ISSUE THREAD

**Issue by mzadrazi** [skallet/minur#4]
- [x] "Start" -> "Od"
- [x] "End" -> "Do"
- [x] "Place" -> "Místo"
- [x] "Count" -> "Počet hráčů"
- [x] "Create" -> "Uložit návrh"
- [x] Validace času: od < do
- [x] Validace počtu hráčů: > 0

**Comment by skallet** [comment]
#9be60d79b96bf36046926184b95911a947113539
#7a9065f4e93329d570509a109bad31d085d00771
