### ISSUE TITLE
TODO - Plánování vzájemného zápasu

### ISSUE THREAD

**Issue by mzadrazi** [skallet/minur#5]
- [x] Odstranit nápovědu (text pod Datum a čas)
- [x] Nedaří se mi zavřít tu bublinu s možností úprav termínu. Bylo by fajn, kdyby zmizela po kliknutí mimo bublinu.
- [x] "Result a/b" -> konkrétní názvy týmů
- [x] "Submit" -> "Uložit skóre"
- [x] "Send" -> "Vložit komentář"
- [x] Poladit barvy, ať je to konzistentní. Komentáře vs. kalendář. Třeba ať je přihlášený tým oranžový.
- [x] Po potvrzení zápasu nezobrazovat kalendář.
